spring:
  application:
    name: microservice-api-gateway
server:
  port: 8070
eureka:
  instance:
    hostname: gateway
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

# 下面整个树都非必须，如果不配置，将默认使用 http://GATEWAY:GATEWAY_PORT/想要访问的Eureka服务id的小写/** 路由到：http://想要访问的Eureka服务id的小写:该服务端口/**
zuul:
  routes:
    user:                                               # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /user/**                                    # 想要映射到的路径
      service-id: microservice-provider-user            # Eureka中的serviceId
auth-server: http://172.17.8.193/cas
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: OC4wNS4wNS4wNy4wMC4wMy4wMS4wMS4w
      client-secret: MC4wNC4wOC4wMi4wMS4wNi4wNC4wMy4w
      access-token-uri: ${auth-server}/oauth2.0/token
      user-authorization-uri: ${auth-server}/oauth2.0/authorize
      scope: read, write
    resource:
      token-info-uri: ${auth-server}/oauth2.0/profile